name: 🧪 Test Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-nuitka-build:
    name: Test Nuitka build on ${{ matrix.os }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            runner: ubuntu-latest
            binary_name: gitautoflow-test-linux
          - os: macos
            runner: macos-latest
            binary_name: gitautoflow-test-macos
          - os: windows
            runner: windows-latest
            binary_name: gitautoflow-test-windows.exe

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install UV (Linux/macOS)
        if: matrix.os != 'windows'
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: 📦 Install UV (Windows)
        if: matrix.os == 'windows'
        run: powershell -c "irm https://astral.sh/uv/install.ps1 | iex"

      - name: 📋 Add UV to PATH (Windows)
        if: matrix.os == 'windows'
        run: echo "$HOME\.cargo\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: 🔧 Install dependencies
        run: |
          uv sync
          uv add nuitka
          uv add ordered-set

      - name: 🏗️ Test build with Nuitka (Linux/macOS)
        if: matrix.os != 'windows'
        run: |
          uv run python -m nuitka \
            --onefile \
            --assume-yes-for-downloads \
            --enable-plugin=anti-bloat \
            --output-filename=${{ matrix.binary_name }} \
            --output-dir=dist/ \
            src/gitautoflow/cli/main.py

      - name: 🏗️ Test build with Nuitka (Windows)
        if: matrix.os == 'windows'
        run: |
          uv run python -m nuitka --onefile --assume-yes-for-downloads --enable-plugin=anti-bloat --output-filename=${{ matrix.binary_name }} --output-dir=dist/ src/gitautoflow/cli/main.py

      - name: ✅ Test binary (Linux/macOS)
        if: matrix.os != 'windows'
        run: |
          chmod +x dist/${{ matrix.binary_name }}
          ./dist/${{ matrix.binary_name }} --help
          ./dist/${{ matrix.binary_name }} version

      - name: ✅ Test binary (Windows)
        if: matrix.os == 'windows'
        run: |
          dist/${{ matrix.binary_name }} --help
          dist/${{ matrix.binary_name }} version

      - name: 📊 Show binary info
        run: |
          ls -la dist/
          file dist/${{ matrix.binary_name }} || true

      - name: 📤 Upload test binary (for debugging)
        uses: actions/upload-artifact@v3
        with:
          name: test-binary-${{ matrix.os }}
          path: dist/${{ matrix.binary_name }}
          retention-days: 1